env: "local"

SERVER_PORT: "8080"
POSTGRES_PORT: "5432"
POSTGRES_USER: "admin"
POSTGRES_NAME: "my_db"
POSTGRES_PASSWORD: "qwerty"
REDIS_PORT: "6379"
REDIS_HOST: "localhost"
REDIS_PASSWORD: "12345"
REDIS_DB: 0
REDIS_POOLSIZE: 50
POSTGRES_HOST: "localhost"
token_ttl: 1h
grpc:
  port: 55055
  timeout: 10h